#ifndef SNP_INCLUDE_SNAP_INTERNAL_PP_HAS_BUILTIN_HPP
#define SNP_INCLUDE_SNAP_INTERNAL_PP_HAS_BUILTIN_HPP

#ifndef SNAP_HAS_BUILTIN
	#ifdef __has_builtin
		#define SNAP_HAS_BUILTIN(BUILTIN) __has_builtin(BUILTIN)
	#else
		#define SNAP_HAS_BUILTIN(BUILTIN) (0)
	#endif // __has_builtin
#endif	   // SNAP_HAS_BUILTIN

#endif // SNP_INCLUDE_SNAP_INTERNAL_PP_HAS_BUILTIN_HPP
