#ifndef SNP_INCLUDE_SNAP_DEBUGGING_BREAKPOINT_IF_DEBUGGING_HPP
#define SNP_INCLUDE_SNAP_DEBUGGING_BREAKPOINT_IF_DEBUGGING_HPP

// Must be included first
#include "snap/internal/abi_namespace.hpp"

SNAP_BEGIN_NAMESPACE

void breakpoint_if_debugging() noexcept;

SNAP_END_NAMESPACE

#endif // SNP_INCLUDE_SNAP_DEBUGGING_BREAKPOINT_IF_DEBUGGING_HPP
