name: ci-windows

on:
  push:
    tags-ignore: [ "v*.*" ]
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: vs22-debug,   configurePreset: vs22, buildPreset: build-vs22-debug,   testPreset: test-vs22-debug }
          - { name: vs22-release, configurePreset: vs22, buildPreset: build-vs22-release, testPreset: test-vs22-release }

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.11.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: |
            out/build
            **/CMakeFiles
            **/CMakeCache.txt
          key: ${{ runner.os }}-${{ matrix.name }}-${{ hashFiles('CMakePresets.json', 'tests/CMakeLists.txt') }}

      - name: Configure
        run: cmake --preset "${{ matrix.configurePreset }}"

      - name: Build
        run: cmake --build --preset "${{ matrix.buildPreset }}" --parallel

      - name: Test
        run: ctest --preset "${{ matrix.testPreset }}" --output-on-failure --schedule-random -F
